apiVersion: apps/v1
kind: Deployment
metadata:
  name: overmindagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overmindagent
  template:
    metadata:
      labels:
        app: overmindagent
    spec:
      containers:
        - name: overmindagent
          image: overmindagent
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: overmindagent-config
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
